#!/usr/bin/env bash
# Generated by michi from shapes.michi. Runs serially under bash. A sweep
# variable shadows a shell variable of the same name.

# data shared
shared_SEEDS=(1 2)

# pipeline first

# data pairs
pairs_X_1=(1 2)
pairs_X_2=('a b' c)

# data late
late_ROWS=10

# step
echo 'it''s' "a;b"

# step pairs
_N=(1 2 3)
_S=('a b' c 'it'\''s')
for _i in "${!_N[@]}"; do
  N=${_N[$_i]}
  S=${_S[$_i]}
  # echo<$N,$S>
  echo $N "$S"
  # for<$N,$S>
  for f in x y; do echo ${late_ROWS} $f; done
done

# step tagged
# true: tag two lines
true

# step both: jobs 2
for _i in "${!pairs_X_1[@]}"; do
  N=${pairs_X_1[$_i]}
  S=${pairs_X_2[$_i]}
  for seed in "${shared_SEEDS[@]}"; do
    for k in x y; do
      # echo<$N,$S,$seed,$k>: timeout 1m
      echo run --seed $seed --k $k $N "$S"
    done
  done
done

# pipeline second: pool 4, placement pack, stderr_dir tmp/first-err,
#   progress marks=ascii color=never, table runs.tbl mode=blocks(headers=once)

for seed in "${shared_SEEDS[@]}"; do
  # step one<$seed>: on_error skip
  echo one $seed

  for k in 1 2; do
    # step nested<$seed,$k>: on_error skip, cores $k
    echo nested $seed $k
  done

  # step two<$seed>: on_error skip, cores $seed
  echo two $seed
done
