#!/usr/bin/env bash
# Generated by michi from syntax.michi. Runs serially under bash. A sweep
# variable shadows a shell variable of the same name.

# data sizes
sizes_THREADS=(1 2 4 8 16)
sizes_SEEDS=(0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95)
sizes_FRACS=(0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0)
sizes_MIXED=(1 2 4 5 6 7 8 16)
sizes_POINTS_1=(5 10 15)
sizes_POINTS_2=(small medium large)

# pipeline bench: pool 8, placement spread, stderr_dir tmp/err,
#   progress marks=unicode, table runs.tbl mode=whole

# data cfg
cfg_ERR='tmp/err'
cfg_ROWS=1000

# data quick
quick_N=(5 10)
quick_K=(a)
quick_Q=(a b)
quick_T=(e)
quick_S=(7.5)

# data full
full_N=(5 10 15)
full_K=(a b)
full_Q=(a b c d)
full_T=(e f g)
full_S=(7.5 10.0 12.0)

# step prep
seq 1 2000 > data.txt

# step count
wc -l < data.txt
wc -c < data.txt

# step burn: jobs 3, cores 2, memory bound, on_error continue
for N in "${quick_N[@]}"; do
  for K in "${quick_K[@]}"; do
    # seq<$N,$K>: name burn-$N-$K, timeout 30s, env N=$N, field N=$N K=$K
    seq 1 ${N}000 | wc -l
  done
done

# step sizes: jobs 2
for _i in "${!sizes_POINTS_1[@]}"; do
  N=${sizes_POINTS_1[$_i]}
  LABEL=${sizes_POINTS_2[$_i]}
  # echo<$N,$LABEL>: name size-$LABEL
  echo $LABEL $(seq 1 ${N}00 | wc -l)
done

# step search: jobs 4
for Q in "${full_Q[@]}"; do
  for T in "${full_T[@]}"; do
    for S in "${full_S[@]}"; do
      # echo<$Q,$T,$S>: field Q=$Q T=$T S=$S
      echo search --s $S $Q $T
    done
  done
done

# step bench
seq 1 ${cfg_ROWS} | sort -n | tail -n 1 > in.txt
for THREADS in "${sizes_THREADS[@]}"; do
  # printf<$THREADS>: timeout 1m
  printf 'threads %s rows %s\n' $THREADS "$(cat in.txt)"
done
for T in 1 2 4; do
  # seq<$T>
  seq 1 $T > "in-$T.txt"
  # wc<$T>
  wc -l < "in-$T.txt"
done
for f in in-*.txt; do wc -l $f; done

for T in "${sizes_THREADS[@]}"; do
  # step scale<$T>: cores $T
  seq 1 $T > "scale-$T.txt"
  wc -l < "scale-$T.txt"
done
