//! A resolved tree as a bash script: data blocks as arrays, sweeps as
//! loops with the command text left for bash to fill, attributes as
//! comments.

use crate::ast::*;
use crate::resolve::Scope;

/// The longest a comment line grows before it wraps.
const WIDTH: usize = 78;

/// The script for a resolved file, named `name` in its header.
pub fn script(file: &File, name: &str) -> String {
    let mut g = Gen {
        out: String::new(),
        depth: 0,
    };
    g.line("#!/usr/bin/env bash");
    g.line(&format!(
        "# Generated by michi from {name}. Runs serially under bash. A sweep"
    ));
    g.line("# variable shadows a shell variable of the same name.");
    for item in &file.items {
        if let Item::Data(data) = item {
            g.blank();
            g.data(data);
        }
    }
    for item in &file.items {
        if let Item::Pipeline(pipeline) = item {
            let scope = Scope::new(file, pipeline);
            g.pipeline(pipeline, &scope);
        }
    }
    g.out
}

struct Gen {
    out: String,
    /// How many loops are open.
    depth: usize,
}

impl Gen {
    fn line(&mut self, text: &str) {
        for _ in 0..self.depth {
            self.out.push_str("  ");
        }
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }

    /// A comment, wrapped at [`WIDTH`] on its `, ` boundaries, with
    /// continuation lines indented under the first.
    /// A comment, wrapped at [`WIDTH`] on its `, ` boundaries, with
    /// continuation lines indented under the first.
    //
    // a newline in an attribute string would end the comment
    // and run the rest as a command, so none survives here
    fn comment(&mut self, head: &str, parts: &[String]) {
        let head = flat(head);
        let parts: Vec<String> = parts.iter().map(|p| flat(p)).collect();
        let mut text = head.clone();
        if !parts.is_empty() {
            text.push_str(": ");
            text.push_str(&parts.join(", "));
        }
        let indent = self.depth * 2;
        if parts.is_empty() || indent + text.len() <= WIDTH {
            self.line(&format!("# {text}"));
            return;
        }
        let mut current = format!("# {head}:");
        for (i, part) in parts.iter().enumerate() {
            let piece = format!(" {part}");
            let sep = if i == 0 { "" } else { "," };
            if i > 0 && indent + current.len() + sep.len() + piece.len() > WIDTH {
                current.push(',');
                self.line(&current);
                current = format!("#  {piece}");
            } else {
                current.push_str(sep);
                current.push_str(&piece);
            }
        }
        self.line(&current);
    }

    // ---

    fn data(&mut self, data: &Data) {
        self.line(&format!("# data {}", data.name.text));
        for entry in &data.entries {
            let var = format!("{}_{}", data.name.text, entry.key.text);
            match &entry.value.kind {
                ValueKind::List(elems) => {
                    let values = list_values(elems);
                    if values.iter().any(|v| matches!(v.kind, ValueKind::Tuple(_))) {
                        let width = values
                            .iter()
                            .map(|v| match &v.kind {
                                ValueKind::Tuple(items) => items.len(),
                                _ => 1,
                            })
                            .max()
                            .unwrap_or(0);
                        for i in 0..width {
                            let column: Vec<String> = values
                                .iter()
                                .map(|v| match &v.kind {
                                    ValueKind::Tuple(items) => quoted(&items[i]),
                                    _ => quoted(v),
                                })
                                .collect();
                            self.line(&format!("{var}_{}=({})", i + 1, column.join(" ")));
                        }
                    } else {
                        let words: Vec<String> = values.iter().map(|v| quoted(v)).collect();
                        self.line(&format!("{var}=({})", words.join(" ")));
                    }
                }
                _ => self.line(&format!("{var}={}", quoted(&entry.value))),
            }
        }
    }

    fn pipeline(&mut self, pipeline: &Pipeline, scope: &Scope<'_>) {
        self.blank();
        let attrs = render_attrs(&pipeline.attrs, scope);
        self.comment(&format!("pipeline {}", pipeline.name.text), &attrs);

        // the pipeline's data first, wherever it was written, so
        // every step finds its arrays set
        for item in &pipeline.items {
            if let PipelineItem::Data(data) = item {
                self.blank();
                self.data(data);
            }
        }
        let mut inst: Vec<String> = Vec::new();
        self.pipeline_items(&pipeline.items, scope, &mut inst, &[], true);
    }

    /// `inst` holds the sweep variables bound around these items, which
    /// label a step. `inherited` are the attributes of the sweep blocks
    /// around them. `sections` separates every item with a blank line,
    /// where inside a loop the first item follows the `do` directly.
    fn pipeline_items(
        &mut self,
        items: &[PipelineItem],
        scope: &Scope<'_>,
        inst: &mut Vec<String>,
        inherited: &[Attr],
        sections: bool,
    ) {
        let mut first = true;
        for item in items {
            if matches!(item, PipelineItem::Data(_)) {
                continue;
            }
            if sections || !first {
                self.blank();
            }
            first = false;
            match item {
                PipelineItem::Data(_) => {}
                PipelineItem::Step(step) => self.step(step, scope, inst, inherited),
                PipelineItem::Sweep(sweep) => {
                    let bound = inst.len();
                    let opened = self.open_loops(&sweep.params, scope, inst);
                    let merged = merge_attrs(inherited, &sweep.attrs);
                    self.pipeline_items(&sweep.body, scope, inst, &merged, false);
                    self.close_loops(opened, inst, bound);
                }
            }
        }
    }

    /// `inherited` are attributes from a sweep block around the step.
    fn step(&mut self, step: &Step, scope: &Scope<'_>, inst: &[String], inherited: &[Attr]) {
        let mut attrs = render_attrs(inherited, scope);
        attrs.extend(render_attrs(&step.attrs, scope));
        let name = step.name.as_ref().map_or("", |n| n.text.as_str());
        let head = format!("step {name}{}", instantiation(inst));
        self.comment(head.trim_end(), &attrs);
        let mut cmd_inst: Vec<String> = Vec::new();
        let opened = match &step.params {
            Some(params) => self.open_loops(params, scope, &mut cmd_inst),
            None => 0,
        };
        self.step_items(&step.body, scope, &mut cmd_inst, &[]);
        self.close_loops(opened, &mut cmd_inst, 0);
    }

    fn step_items(
        &mut self,
        items: &[StepItem],
        scope: &Scope<'_>,
        inst: &mut Vec<String>,
        inherited: &[Attr],
    ) {
        for item in items {
            match item {
                StepItem::Command(command) => self.command(command, scope, inst, inherited),
                StepItem::Sweep(sweep) => {
                    let bound = inst.len();
                    let opened = self.open_loops(&sweep.params, scope, inst);
                    let merged = merge_attrs(inherited, &sweep.attrs);
                    self.step_items(&sweep.body, scope, inst, &merged);
                    self.close_loops(opened, inst, bound);
                }
            }
        }
    }

    fn command(
        &mut self,
        command: &Command,
        scope: &Scope<'_>,
        inst: &[String],
        inherited: &[Attr],
    ) {
        let mut attrs = render_attrs(inherited, scope);
        attrs.extend(render_attrs(&command.attrs, scope));
        let text = shell_text(&command.text);
        if !inst.is_empty() || !attrs.is_empty() {
            let label = text.split_whitespace().next().unwrap_or("");
            let head = format!("{label}{}", instantiation(inst));
            self.comment(&head, &attrs);
        }
        self.line(&text);
    }

    // ---

    /// Open one loop per binding, push the names it binds onto `inst`,
    /// and return how many loops opened.
    fn open_loops(&mut self, params: &Params, scope: &Scope<'_>, inst: &mut Vec<String>) -> usize {
        let mut opened = 0;
        for binding in &params.bindings {
            match &binding.pattern {
                Pattern::One(name) => {
                    let over = match &binding.list.kind {
                        ValueKind::Path(block, key) => {
                            format!("\"${{{}_{}[@]}}\"", block.text, key.text)
                        }
                        ValueKind::List(elems) => list_values(elems)
                            .iter()
                            .map(|v| quoted(v))
                            .collect::<Vec<_>>()
                            .join(" "),
                        _ => String::new(),
                    };
                    self.line(&format!("for {} in {over}; do", name.text));
                    self.depth += 1;
                    inst.push(name.text.clone());
                }
                Pattern::Tuple(names) => {
                    let prefix = match &binding.list.kind {
                        ValueKind::Path(block, key) => format!("{}_{}", block.text, key.text),
                        ValueKind::List(elems) => {
                            // an inline tuple list has no data block to
                            // hold it, so its columns are arrays named
                            // after the pattern, under the `_` that no
                            // michi name may start with
                            let values = list_values(elems);
                            for (i, name) in names.iter().enumerate() {
                                let column: Vec<String> = values
                                    .iter()
                                    .map(|v| match &v.kind {
                                        ValueKind::Tuple(items) => quoted(&items[i]),
                                        _ => quoted(v),
                                    })
                                    .collect();
                                self.line(&format!("_{}=({})", name.text, column.join(" ")));
                            }
                            String::new()
                        }
                        _ => String::new(),
                    };
                    let column = |i: usize| {
                        if prefix.is_empty() {
                            format!("_{}", names[i].text)
                        } else {
                            format!("{prefix}_{}", i + 1)
                        }
                    };
                    self.line(&format!("for _i in \"${{!{}[@]}}\"; do", column(0)));
                    self.depth += 1;
                    for (i, name) in names.iter().enumerate() {
                        self.line(&format!("{}=${{{}[$_i]}}", name.text, column(i)));
                        inst.push(name.text.clone());
                    }
                }
            }
            opened += 1;
        }
        let _ = scope;
        opened
    }

    /// Close `opened` loops and forget the names bound since `inst` had
    /// `bound` entries.
    fn close_loops(&mut self, opened: usize, inst: &mut Vec<String>, bound: usize) {
        for _ in 0..opened {
            self.depth -= 1;
            self.line("done");
        }
        inst.truncate(bound);
    }
}

/// `outer` then `inner`, so an item's own attributes read last.
fn merge_attrs(outer: &[Attr], inner: &[Attr]) -> Vec<Attr> {
    outer.iter().chain(inner).map(clone_attr).collect()
}

/// `text` on one line.
fn flat(text: &str) -> String {
    text.replace(['\n', '\r'], " ")
}

fn clone_attr(attr: &Attr) -> Attr {
    Attr {
        name: attr.name.clone(),
        args: attr
            .args
            .iter()
            .map(|arg| Arg {
                key: arg.key.clone(),
                value: clone_value(&arg.value),
            })
            .collect(),
        span: attr.span,
    }
}

fn clone_value(value: &Value) -> Value {
    let kind = match &value.kind {
        ValueKind::Int(n) => ValueKind::Int(*n),
        ValueKind::Float { value, text } => ValueKind::Float {
            value: *value,
            text: text.clone(),
        },
        ValueKind::Duration { value, text } => ValueKind::Duration {
            value: *value,
            text: text.clone(),
        },
        ValueKind::Ident(s) => ValueKind::Ident(s.clone()),
        ValueKind::Str(t) => ValueKind::Str(t.clone()),
        ValueKind::Var(s) => ValueKind::Var(s.clone()),
        ValueKind::Path(a, b) => ValueKind::Path(a.clone(), b.clone()),
        ValueKind::List(elems) => ValueKind::List(
            elems
                .iter()
                .map(|e| match e {
                    Elem::Value(v) => Elem::Value(clone_value(v)),
                    Elem::Range(_) => unreachable!("ranges are evaluated before the script"),
                })
                .collect(),
        ),
        ValueKind::Tuple(values) => ValueKind::Tuple(values.iter().map(clone_value).collect()),
        ValueKind::Call(name, args) => ValueKind::Call(
            name.clone(),
            args.iter()
                .map(|arg| Arg {
                    key: arg.key.clone(),
                    value: clone_value(&arg.value),
                })
                .collect(),
        ),
    };
    Value {
        kind,
        span: value.span,
    }
}

/// `<$A,$B>` for the variables an item is instantiated under, or nothing.
fn instantiation(inst: &[String]) -> String {
    if inst.is_empty() {
        return String::new();
    }
    let vars: Vec<String> = inst.iter().map(|n| format!("${n}")).collect();
    format!("<{}>", vars.join(","))
}

/// The values of a list with no ranges left in it.
fn list_values(elems: &[Elem]) -> Vec<&Value> {
    elems
        .iter()
        .map(|e| match e {
            Elem::Value(v) => v,
            Elem::Range(_) => unreachable!("ranges are evaluated before the script"),
        })
        .collect()
}

/// Command text for the script: `${block.KEY}` becomes `${block_KEY}`,
/// every other reference stays as written for bash. A raw string goes
/// through the same, since its literal parts are untouched.
fn shell_text(text: &Text) -> String {
    let mut out = String::new();
    for part in &text.parts {
        match part {
            Part::Lit(s) => out.push_str(s),
            Part::Var { name, braced } if name.contains('.') => {
                let _ = braced;
                out.push_str("${");
                out.push_str(&name.replace('.', "_"));
                out.push('}');
            }
            Part::Var { name, braced: true } => {
                out.push_str("${");
                out.push_str(name);
                out.push('}');
            }
            Part::Var {
                name,
                braced: false,
            } => {
                out.push('$');
                out.push_str(name);
            }
        }
    }
    out
}

/// A value as a word in the script: a string is single-quoted, anything
/// else is bare unless bash would read into it.
fn quoted(value: &Value) -> String {
    let text = plain(value, None);
    let safe = !matches!(value.kind, ValueKind::Str(_))
        && !text.is_empty()
        && text
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"_./+-".contains(&b));
    if safe {
        text
    } else {
        format!("'{}'", text.replace('\'', "'\\''"))
    }
}

/// A value as it reads in a comment, with a data path replaced by what
/// it names when a scope is given.
fn plain(value: &Value, scope: Option<&Scope<'_>>) -> String {
    match &value.kind {
        ValueKind::Int(n) => n.to_string(),
        ValueKind::Float { text, .. } | ValueKind::Duration { text, .. } => text.clone(),
        ValueKind::Ident(s) => s.clone(),
        ValueKind::Str(t) => t.source(),
        ValueKind::Var(name) => format!("${name}"),
        ValueKind::Path(block, key) => match scope.and_then(|s| s.lookup(&block.text, &key.text)) {
            Some(target) => plain(target, scope),
            None => format!("{}.{}", block.text, key.text),
        },
        ValueKind::List(elems) => {
            let words: Vec<String> = list_values(elems).iter().map(|v| plain(v, scope)).collect();
            format!("[{}]", words.join(", "))
        }
        ValueKind::Tuple(values) => {
            let words: Vec<String> = values.iter().map(|v| plain(v, scope)).collect();
            format!("({})", words.join(", "))
        }
        ValueKind::Call(name, args) => {
            format!(
                "{}({})",
                name.text,
                render_args(args, scope, false).join(", ")
            )
        }
    }
}

/// Arguments as they read in a comment. In `field`, a bare `$N` records N
/// under its own name, so it reads `N=$N`.
fn render_args(args: &[Arg], scope: Option<&Scope<'_>>, field: bool) -> Vec<String> {
    args.iter()
        .map(|arg| match (&arg.key, &arg.value.kind) {
            (Some(key), _) => format!("{}={}", key.text, plain(&arg.value, scope)),
            (None, ValueKind::Var(name)) if field => format!("{name}=${name}"),
            (None, _) => plain(&arg.value, scope),
        })
        .collect()
}

/// Each attribute as `name arg arg`, for a comment.
fn render_attrs(attrs: &[Attr], scope: &Scope<'_>) -> Vec<String> {
    attrs
        .iter()
        .map(|attr| {
            let args = render_args(&attr.args, Some(scope), attr.name.text == "field");
            if args.is_empty() {
                attr.name.text.clone()
            } else {
                format!("{} {}", attr.name.text, args.join(" "))
            }
        })
        .collect()
}
